id: A8499506E
title: 'Ocean of Offering Clouds: A Light Offering Prayer'
type: translation
pechas:
- I9C4DDD55
- I272554D4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:14.049073
  last_modified_at: 2023-01-04 11:56:14.049084
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I9C4DDD55/725F: 568C
  I272554D4/67C6: 568C
